
minetest.register_alias("mcl_core:apple","mcl_trees:apple")
minetest.register_alias("mcl_core:paper","mcl_trees:paper")

minetest.register_alias("default:acacia_tree", "mcl_core:acaciatree")
minetest.register_alias("default:acacia_leaves", "mcl_core:acacialeaves")

minetest.register_alias("mcl_core:birchtree","mcl_trees:tree_birch")
minetest.register_alias("mcl_core:darktree","mcl_trees:tree_dark_oak")
minetest.register_alias("mcl_core:acaciatree","mcl_trees:tree_acacia")
minetest.register_alias("mcl_core:jungletree","mcl_trees:tree_jungle")
minetest.register_alias("mcl_core:sprucetree","mcl_trees:tree_spruce")
minetest.register_alias("mcl_core:tree","mcl_trees:tree_oak")
minetest.register_alias("default:tree","mcl_trees:tree_oak")
minetest.register_alias("mcl_mangrove:mangrove_tree","mcl_trees:tree_mangrove")
minetest.register_alias("mcl_crimson:crimson_hyphae","mcl_trees:tree_crimson")
minetest.register_alias("mcl_crimson:warped_hyphae","mcl_trees:tree_warped")

minetest.register_alias("mcl_core:birchleaves","mcl_trees:leaves_birch")
minetest.register_alias("mcl_core:darkleaves","mcl_trees:leaves_dark_oak")
minetest.register_alias("mcl_core:acacialeaves","mcl_trees:leaves_acacia")
minetest.register_alias("mcl_core:jungleleaves","mcl_trees:leaves_jungle")
minetest.register_alias("mcl_core:spruceleaves","mcl_trees:leaves_spruce")
minetest.register_alias("mcl_core:leaves","mcl_trees:leaves_oak")
minetest.register_alias("default:leaves","mcl_trees:leaves_oak")
minetest.register_alias("mcl_mangrove:mangroveleaves","mcl_trees:leaves_mangrove")

minetest.register_alias("mcl_core:birchwood","mcl_trees:planks_birch")
minetest.register_alias("mcl_core:big_oakwood","mcl_trees:planks_dark_oak")
minetest.register_alias("mcl_core:darkwood","mcl_trees:planks_dark_oak")
minetest.register_alias("mcl_core:acaciawood","mcl_trees:planks_acacia")
minetest.register_alias("mcl_core:junglewood","mcl_trees:planks_jungle")
minetest.register_alias("mcl_core:sprucewood","mcl_trees:planks_spruce")
minetest.register_alias("mcl_core:wood","mcl_trees:planks_oak")
minetest.register_alias("mcl_crimson:warped_hyphae_wood","mcl_trees:planks_warped")
minetest.register_alias("mcl_crimson:crimson_hyphae_wood","mcl_trees:planks_crimson")
minetest.register_alias("mcl_mangrove:mangrove_wood","mcl_trees:planks_mangrove")
minetest.register_alias("default:wood","mcl_trees:planks_oak")

minetest.register_alias("mcl_core:birchtree_bark","mcl_trees:bark_birch")
minetest.register_alias("mcl_core:big_oaktree_bark","mcl_trees:bark_dark_oak")
minetest.register_alias("mcl_core:darktree_bark","mcl_trees:bark_dark_oak")
minetest.register_alias("mcl_core:acaciatree_bark","mcl_trees:bark_acacia")
minetest.register_alias("mcl_core:jungletree_bark","mcl_trees:bark_jungle")
minetest.register_alias("mcl_core:sprucetree_bark","mcl_trees:bark_spruce")
minetest.register_alias("mcl_core:tree_bark","mcl_trees:bark_oak")
minetest.register_alias("mcl_crimson:warped_hyphae_bark","mcl_trees:bark_warped")
minetest.register_alias("mcl_crimson:crimson_hyphae_bark","mcl_trees:bark_crimson")
minetest.register_alias("mcl_mangrove:mangrove_tree_bark","mcl_trees:bark_mangrove")

minetest.register_alias("mcl_core:birchsapling","mcl_trees:sapling_birch")
minetest.register_alias("mcl_core:big_oaksapling","mcl_trees:sapling_dark_oak")
minetest.register_alias("mcl_core:darksapling","mcl_trees:sapling_dark_oak")
minetest.register_alias("mcl_core:acaciasapling","mcl_trees:sapling_acacia")
minetest.register_alias("mcl_core:junglesapling","mcl_trees:sapling_jungle")
minetest.register_alias("mcl_core:sprucesapling","mcl_trees:sapling_spruce")
minetest.register_alias("mcl_core:sapling","mcl_trees:sapling_oak")
minetest.register_alias("default:sapling","mcl_trees:sapling_oak")

minetest.register_alias("mcl_fences:fence","mcl_fences:oak_fence")
minetest.register_alias("mcl_fences:jungle_fence","mcl_fences:jungle_fence")
minetest.register_alias("mcl_fences:acacia_fence","mcl_fences:acacia_fence")
minetest.register_alias("mcl_fences:darkwood_fence","mcl_fences:dark_oak_fence")
minetest.register_alias("mcl_fences:dark_oak_fence","mcl_fences:dark_oak_fence")
minetest.register_alias("mcl_fences:spruce_fence","mcl_fences:spruce_fence")
minetest.register_alias("mcl_fences:birch_fence","mcl_fences:birch_fence")
minetest.register_alias("mcl_mangrove:mangrove_wood_fence","mcl_fences:mangrove_fence")
minetest.register_alias("mcl_crimson:crimson_fence","mcl_fences:crimson_fence")
minetest.register_alias("mcl_crimson:warped_fence","mcl_fences:warped_fence")
--minetest.register_alias("mcl_fences:nether_brick_fence","mcl_stone:nether_bricks_fence")
--minetest.register_alias("mcl_fences:red_nether_brick_fence","mcl_stone:red_nether_bricks_fence")

minetest.register_alias("mcl_fences:fence_gate","mcl_fences:oak_fence_gate")
minetest.register_alias("mcl_fences:jungle_fence_gate","mcl_fences:jungle_fence_gate")
minetest.register_alias("mcl_fences:acacia_fence_gate","mcl_fences:acacia_fence_gate")
minetest.register_alias("mcl_fences:darkwood_fence_gate","mcl_fences:dark_oak_fence_gate")
minetest.register_alias("mcl_fences:dark_oak_fence_gate","mcl_fences:dark_oak_fence_gate")
minetest.register_alias("mcl_fences:spruce_fence_gate","mcl_fences:spruce_fence_gate")
minetest.register_alias("mcl_fences:birch_fence_gate","mcl_fences:birch_fence_gate")
minetest.register_alias("mcl_mangrove:mangrove_wood_fence_gate","mcl_fences:mangrove_fence_gate")
minetest.register_alias("mcl_crimson:crimson_fence_gate","mcl_fences:crimson_fence_gate")
minetest.register_alias("mcl_crimson:warped_fence_gate","mcl_fences:warped_fence_gate")
--minetest.register_alias("mcl_fences:nether_brick_fence_gate","mcl_stone:nether_brick_fence_gate")
--minetest.register_alias("mcl_fences:red_nether_brick_fence_gate","mcl_stone:red_nether_brick_fence_gate")

--[[

--]]
minetest.register_alias("mcl_doors:wooden_door","mcl_doors:door_oak")
minetest.register_alias("mcl_doors:jungle_door","mcl_doors:door_jungle")
minetest.register_alias("mcl_doors:acacia_door","mcl_doors:door_acacia")
minetest.register_alias("mcl_doors:dark_door","mcl_doors:door_dark_oak")
minetest.register_alias("mcl_doors:spruce_door","mcl_doors:door_spruce")
minetest.register_alias("mcl_doors:birch_door","mcl_doors:door_birch")
minetest.register_alias("mcl_mangrove:mangrove_door","mcl_doors:door_mangrove")
minetest.register_alias("mcl_crimson:warped_door","mcl_trees:door_warped")
minetest.register_alias("mcl_crimson:crimson_door","mcl_trees:door_crimson")

minetest.register_alias("mcl_mangrove:mangrove_door","mcl_trees:door_mangrove")
minetest.register_alias("mcl_crimson:warped_door","mcl_trees:door_warped")
minetest.register_alias("mcl_crimson:crimson_door","mcl_trees:door_crimson")

minetest.register_alias("mcl_doors:wooden_door_b_1","mcl_doors:door_oak_b_1")
minetest.register_alias("mcl_doors:jungle_door_b_1","mcl_doors:door_jungle_b_1")
minetest.register_alias("mcl_doors:acacia_door_b_1","mcl_doors:door_acacia_b_1")
minetest.register_alias("mcl_doors:dark_oak_door_b_1","mcl_doors:door_dark_oak_b_1")
minetest.register_alias("mcl_doors:spruce_door_b_1","mcl_doors:door_spruce_b_1")
minetest.register_alias("mcl_doors:birch_door_b_1","mcl_doors:door_birch_b_1")
minetest.register_alias("mcl_mangrove:mangrove_door_b_1","mcl_doors:door_mangrove_b_1")
minetest.register_alias("mcl_crimson:warped_door_b_1","mcl_doors:door_warped_b_1")
minetest.register_alias("mcl_crimson:crimson_door_b_1","mcl_doors:door_crimson_b_1")

minetest.register_alias("mcl_doors:wooden_door_t_1","mcl_doors:door_oak_t_1")
minetest.register_alias("mcl_doors:jungle_door_t_1","mcl_doors:door_jungle_t_1")
minetest.register_alias("mcl_doors:acacia_door_t_1","mcl_doors:door_acacia_t_1")
minetest.register_alias("mcl_doors:dark_oak_door_t_1","mcl_doors:door_dark_oak_t_1")
minetest.register_alias("mcl_doors:spruce_door_t_1","mcl_doors:door_spruce_t_1")
minetest.register_alias("mcl_doors:birch_door_t_1","mcl_doors:door_birch_t_1")
minetest.register_alias("mcl_mangrove:mangrove_door_t_1","mcl_doors:door_mangrove_t_1")
minetest.register_alias("mcl_crimson:warped_door_t_1","mcl_doors:door_warped_t_1")
minetest.register_alias("mcl_crimson:crimson_door_t_1","mcl_doors:door_crimson_t_1")


minetest.register_alias("mcl_doors:wooden_door_b_2","mcl_doors:door_oak_b_2")
minetest.register_alias("mcl_doors:jungle_door_b_2","mcl_doors:door_jungle_b_2")
minetest.register_alias("mcl_doors:acacia_door_b_2","mcl_doors:door_acacia_b_2")
minetest.register_alias("mcl_doors:dark_oak_door_b_2","mcl_doors:door_dark_oak_b_2")
minetest.register_alias("mcl_doors:spruce_door_b_2","mcl_doors:door_spruce_b_2")
minetest.register_alias("mcl_doors:birch_door_b_2","mcl_doors:door_birch_b_2")
minetest.register_alias("mcl_mangrove:mangrove_door_b_2","mcl_doors:door_mangrove_b_2")
minetest.register_alias("mcl_crimson:warped_door_b_2","mcl_doors:door_warped_b_2")
minetest.register_alias("mcl_crimson:crimson_door_b_2","mcl_doors:door_crimson_b_2")

minetest.register_alias("mcl_doors:wooden_door_t_2","mcl_doors:door_oak_t_2")
minetest.register_alias("mcl_doors:jungle_door_t_2","mcl_doors:door_jungle_t_2")
minetest.register_alias("mcl_doors:acacia_door_t_2","mcl_doors:door_acacia_t_2")
minetest.register_alias("mcl_doors:dark_oak_door_t_2","mcl_doors:door_dark_oak_t_2")
minetest.register_alias("mcl_doors:spruce_door_t_2","mcl_doors:door_spruce_t_2")
minetest.register_alias("mcl_doors:birch_door_t_2","mcl_doors:door_birch_t_2")
minetest.register_alias("mcl_mangrove:mangrove_door_t_2","mcl_doors:door_mangrove_t_2")
minetest.register_alias("mcl_crimson:warped_door_t_2","mcl_doors:door_warped_t_2")
minetest.register_alias("mcl_crimson:crimson_door_t_2","mcl_doors:door_crimson_t_2")

minetest.register_alias("mcl_doors:trapdoor","mcl_doors:trapdoor_oak")
minetest.register_alias("mcl_doors:spruce_trapdoor","mcl_doors:trapdoor_spruce")
minetest.register_alias("mcl_doors:birch_trapdoor","mcl_doors:trapdoor_birch")
minetest.register_alias("mcl_doors:acacia_trapdoor","mcl_doors:trapdoor_acacia")
minetest.register_alias("mcl_doors:jungle_trapdoor","mcl_doors:trapdoor_jungle")
minetest.register_alias("mcl_doors:dark_oak_trapdoor","mcl_doors:trapdoor_dark_oak")
minetest.register_alias("mcl_mangrove:mangrove_trapdoor","mcl_doors:trapdoor_mangrove")
minetest.register_alias("mcl_crimson:warped_trapdoor","mcl_doors:trapdoor_warped")
minetest.register_alias("mcl_crimson:crimson_trapdoor","mcl_doors:trapdoor_crimson")

minetest.register_alias("mcl_doors:trapdoor_open","mcl_doors:trapdoor_oak_open")
minetest.register_alias("mcl_doors:spruce_trapdoor_open","mcl_doors:trapdoor_spruce_open")
minetest.register_alias("mcl_doors:birch_trapdoor_open","mcl_doors:trapdoor_birch_open")
minetest.register_alias("mcl_doors:acacia_trapdoor_open","mcl_doors:trapdoor_acacia_open")
minetest.register_alias("mcl_doors:jungle_trapdoor_open","mcl_doors:trapdoor_jungle_open")
minetest.register_alias("mcl_doors:dark_oak_trapdoor_open","mcl_doors:trapdoor_dark_oak_open")
minetest.register_alias("mcl_mangrove:mangrove_trapdoor_open","mcl_doors:trapdoor_mangrove_open")
minetest.register_alias("mcl_crimson:warped_trapdoor_open","mcl_doors:trapdoor_warped_hyphae_open")
minetest.register_alias("mcl_crimson:crimson_trapdoor_open","mcl_doors:trapdoor_crimson_hyphae_open")

minetest.register_alias("mcl_crimson:crimson_door","mcl_doors:door_crimson")
minetest.register_alias("mcl_crimson:warped_door","mcl_doors:door_warped")
minetest.register_alias("mcl_doors:dark_oak_door","mcl_doors:door_dark_oak")
minetest.register_alias("mcl_crimson:crimson_trapdoor_open","mcl_doors:trapdoor_crimson_open")
minetest.register_alias("mcl_crimson:warped_trapdoor_open","mcl_doors:trapdoor_warped_open")
minetest.register_alias("mcl_mangrove:mangrove_door","mcl_doors:door_mangrove")
minetest.register_alias("mcl_mangrove:mangrove_wood_fence_gate_open","mcl_trees:planks_mangrove_fence_gate_open")

minetest.register_alias("mcl_crimson:warped_fence_gate_open","mcl_trees:planks_warped_fence_gate_open")
minetest.register_alias("mcl_crimson:crimson_fence_gate_open","mcl_trees:planks_crimson_fence_gate_open")
minetest.register_alias("mcl_fences:acacia_fence_gate_open","mcl_trees:planks_acacia_fence_gate_open")
minetest.register_alias("mcl_fences:birch_fence_gate_open","mcl_trees:planks_birch_fence_gate_open")
minetest.register_alias("mcl_fences:dark_oak_fence_gate_open","mcl_trees:planks_dark_oak_fence_gate_open")
minetest.register_alias("mcl_fences:fence_gate_open","mcl_trees:planks_oak_fence_gate_open")
minetest.register_alias("mcl_fences:jungle_fence_gate_open","mcl_trees:planks_jungle_fence_gate_open")
minetest.register_alias("mcl_fences:spruce_fence_gate_open","mcl_trees:planks_spruce_fence_gate_open")

minetest.register_alias("mclx_fences:nether_brick_fence_gate","mcl_stone:nether_bricks_fence_gate")
minetest.register_alias("mclx_fences:nether_brick_fence_gate_open","mcl_stone:nether_bricks_fence_gate_open")
minetest.register_alias("mclx_fences:red_nether_brick_fence","mcl_stone:red_nether_bricks_fence")
minetest.register_alias("mclx_fences:red_nether_brick_fence_gate","mcl_stone:red_nether_bricks_fence_gate")
minetest.register_alias("mclx_fences:red_nether_brick_fence_gate_open","mcl_stone:red_nether_bricks_fence_gate_open")


minetest.register_alias("mcl_core:stripped_oak","mcl_trees:stripped_oak")
minetest.register_alias("mcl_core:stripped_jungle","mcl_trees:stripped_jungle")
minetest.register_alias("mcl_core:stripped_acacia","mcl_trees:stripped_acacia")
minetest.register_alias("mcl_core:stripped_dark_oak","mcl_trees:stripped_dark_oak")
minetest.register_alias("mcl_core:stripped_spruce","mcl_trees:stripped_spruce")
minetest.register_alias("mcl_core:stripped_birch","mcl_trees:stripped_birch")
minetest.register_alias("mcl_mangrove:mangrove_stripped_trunk","mcl_trees:stripped_mangrove")
minetest.register_alias("mcl_crimson:stripped_warped_hyphae","mcl_trees:stripped_warped")
minetest.register_alias("mcl_crimson:stripped_crimson_hyphae","mcl_trees:stripped_crimson")

minetest.register_alias("mcl_core:stripped_oak_bark","mcl_trees:bark_stripped_oak")
minetest.register_alias("mcl_core:stripped_jungle_bark","mcl_trees:bark_stripped_jungle")
minetest.register_alias("mcl_core:stripped_acacia_bark","mcl_trees:bark_stripped_acacia")
minetest.register_alias("mcl_core:stripped_dark_oak_bark","mcl_trees:bark_stripped_dark_oak")
minetest.register_alias("mcl_core:stripped_spruce_bark","mcl_trees:bark_stripped_spruce")
minetest.register_alias("mcl_core:stripped_birch_bark","mcl_trees:bark_stripped_birch")
minetest.register_alias("mcl_mangrove:mangrove_stripped_bark","mcl_trees:bark_stripped_mangrove")
minetest.register_alias("mcl_crimson:stripped_warped_hyphae_bark","mcl_trees:bark_stripped_warped")
minetest.register_alias("mcl_crimson:stripped_crimson_hyphae_bark","mcl_trees:bark_stripped_crimson")

minetest.register_alias("redstone_button:button_wood_off","mcl_trees:planks_oak_button_off")
minetest.register_alias("redstone_button:button_acaciawood_off","mcl_trees:planks_acacia_button_off")
minetest.register_alias("redstone_button:button_birchwood_off","mcl_trees:planks_birch_button_off")
minetest.register_alias("redstone_button:button_junglewood_off","mcl_trees:planks_jungle_button_off")
minetest.register_alias("redstone_button:button_darkwood_off","mcl_trees:planks_dark_oak_button_off")
minetest.register_alias("redstone_button:button_sprucewood_off","mcl_trees:planks_spruce_button_off")
minetest.register_alias("redstone_button:button_mangrove_wood_off","mcl_trees:planks_mangrove_button_off")
minetest.register_alias("redstone_button:button_warped_hyphae_wood_off","mcl_trees:planks_warped_button_off")
minetest.register_alias("redstone_button:button_crimson_hyphae_wood_off","mcl_trees:planks_crimson_button_off")

minetest.register_alias("redstone_button:button_wood_on","mcl_trees:planks_oak_button_on")
minetest.register_alias("redstone_button:button_acaciawood_on","mcl_trees:planks_acacia_button_on")
minetest.register_alias("redstone_button:button_birchwood_on","mcl_trees:planks_birch_button_on")
minetest.register_alias("redstone_button:button_junglewood_on","mcl_trees:planks_jungle_button_on")
minetest.register_alias("redstone_button:button_darkwood_on","mcl_trees:planks_dark_oak_button_on")
minetest.register_alias("redstone_button:button_sprucewood_on","mcl_trees:planks_spruce_button_on")
minetest.register_alias("redstone_button:button_mangrove_wood_on","mcl_trees:planks_mangrove_button_on")
minetest.register_alias("redstone_button:button_warped_hyphae_wood_on","mcl_trees:planks_warped_button_on")
minetest.register_alias("redstone_button:button_crimson_hyphae_wood_on","mcl_trees:planks_crimson_button_on")

minetest.register_alias("redstone_pressureplates:pressure_plate_wood_off","mcl_trees:planks_oak_pplate_off")
minetest.register_alias("redstone_pressureplates:pressure_plate_acaciawood_off","mcl_trees:planks_acacia_pplate_off")
minetest.register_alias("redstone_pressureplates:pressure_plate_birchwood_off","mcl_trees:planks_birch_pplate_off")
minetest.register_alias("redstone_pressureplates:pressure_plate_junglewood_off","mcl_trees:planks_jungle_pplate_off")
minetest.register_alias("redstone_pressureplates:pressure_plate_darkwood_off","mcl_trees:planks_dark_oak_pplate_off")
minetest.register_alias("redstone_pressureplates:pressure_plate_sprucewood_off","mcl_trees:planks_spruce_pplate_off")
minetest.register_alias("redstone_pressureplates:pressure_plate_mangrove_wood_off","mcl_trees:planks_mangrove_pplate_off")
minetest.register_alias("redstone_pressureplates:pressure_plate_warped_hyphae_wood_off","mcl_trees:planks_warped_pplate_off")
minetest.register_alias("redstone_pressureplates:pressure_plate_crimson_hyphae_wood_off","mcl_trees:planks_crimson_pplate_off")

minetest.register_alias("redstone_pressureplates:pressure_plate_wood_on","mcl_trees:planks_oak_pplate_on")
minetest.register_alias("redstone_pressureplates:pressure_plate_acaciawood_on","mcl_trees:planks_acacia_pplate_on")
minetest.register_alias("redstone_pressureplates:pressure_plate_birchwood_on","mcl_trees:planks_birch_pplate_on")
minetest.register_alias("redstone_pressureplates:pressure_plate_junglewood_on","mcl_trees:planks_jungle_pplate_on")
minetest.register_alias("redstone_pressureplates:pressure_plate_darkwood_on","mcl_trees:planks_dark_oak_pplate_on")
minetest.register_alias("redstone_pressureplates:pressure_plate_sprucewood_on","mcl_trees:planks_spruce_pplate_on")
minetest.register_alias("redstone_pressureplates:pressure_plate_mangrove_wood_on","mcl_trees:planks_mangrove_pplate_on")
minetest.register_alias("redstone_pressureplates:pressure_plate_warped_hyphae_wood_on","mcl_trees:planks_warped_pplate_on")
minetest.register_alias("redstone_pressureplates:pressure_plate_crimson_hyphae_wood_on","mcl_trees:planks_crimson_pplate_on")

minetest.register_alias("mcl_mangrove:mangrove_roots","mcl_trees:mangrove_roots")
minetest.register_alias("mcl_mangrove:propagule","mcl_trees:mangrove_propagule")
minetest.register_alias("mcl_mangrove:propagule_clay_block","mcl_trees:mangrove_propagule_block_clay")
minetest.register_alias("mcl_mangrove:hanging_propagule","mcl_trees:mangrove_propagule_hanging")
minetest.register_alias("mcl_mangrove:hanging_propagule_1","mcl_trees:mangrove_propagule_hanging")


minetest.register_alias("mcl_mangrove:water_logged_roots","mcl_trees:mangrove_roots_water_logged")
minetest.register_alias("mcl_mangrove:river_water_logged_roots","mcl_trees:mangrove_roots_river_water_logged")
minetest.register_alias("mcl_mangrove:mangrove_mud_roots","mcl_trees:mangrove_roots_mud")

local propagule_water_nodes = {"mcl_stone:mud","mcl_flora:dirt","mcl_flora:dirt_coarse"}
for _,root in pairs(propagule_water_nodes) do
	local r = root:split(":")[2]
	minetest.register_alias("mcl_mangrove:propagule_"..r,"mcl_trees:propagule_"..r)
end

local function alias_signs(oldwood,newwood)
	minetest.register_alias("mcl_signs:wall_sign"..oldwood, "mcl_signs:wall_sign".. newwood)
	minetest.register_alias("mcl_signs:standing_sign"..oldwood, "mcl_signs:standing_sign".. newwood)
	minetest.register_alias("mcl_signs:standing_sign22_5"..oldwood, "mcl_signs:standing_sign22_5".. newwood)
	minetest.register_alias("mcl_signs:standing_sign45"..oldwood, "mcl_signs:standing_sign45".. newwood)
	minetest.register_alias("mcl_signs:standing_sign67_5"..oldwood, "mcl_signs:standing_sign67_5".. newwood)
end

alias_signs("","_oak")
alias_signs("_acaciawood","_acacia")
alias_signs("_junglewood","_jungle")
alias_signs("_birchwood","_birch")
alias_signs("_darkwood","_dark_oak")
alias_signs("_sprucewood","_spruce")
alias_signs("_mangrove_wood","_mangrove")
alias_signs("_crimson_hyphae_wood","_crimson")
alias_signs("_warped_hyphae_wood","_warped")

minetest.register_alias("mcl_boats:boat","mcl_trees:boat_oak")
minetest.register_alias("mcl_boats:boat_acacia","mcl_trees:boat_acacia")
minetest.register_alias("mcl_boats:boat_birch","mcl_trees:boat_birch")
minetest.register_alias("mcl_boats:boat_dark_oak","mcl_trees:boat_dark_oak")
minetest.register_alias("mcl_boats:boat_jungle","mcl_trees:boat_jungle")
minetest.register_alias("mcl_boats:boat_mangrove","mcl_trees:boat_mangrove")
minetest.register_alias("mcl_boats:boat_obsidian","mcl_trees:boat_obsidian")
minetest.register_alias("mcl_boats:boat_spruce","mcl_trees:boat_spruce")
minetest.register_alias("mcl_boats:chest_boat","mcl_trees:chest_boat_oak")
minetest.register_alias("mcl_boats:chest_boat_acacia","mcl_trees:chest_boat_acacia")
minetest.register_alias("mcl_boats:chest_boat_birch","mcl_trees:chest_boat_birch")
minetest.register_alias("mcl_boats:chest_boat_dark_oak","mcl_trees:chest_boat_dark_oak")
minetest.register_alias("mcl_boats:chest_boat_jungle","mcl_trees:chest_boat_jungle")
minetest.register_alias("mcl_boats:chest_boat_mangrove","mcl_trees:chest_boat_mangrove")
minetest.register_alias("mcl_boats:chest_boat_spruce","mcl_trees:chest_boat_spruce")
minetest.register_alias("mcl_boats:boat_obsidian","mcl_trees:boat_oak")

minetest.register_alias("mcl_core:ladder","mcl_trees:ladder")
minetest.register_alias("mcl_core:bowl","mcl_trees:bowl")
minetest.register_alias("mcl_core:brick","mcl_stone:bricks")
minetest.register_alias("mcl_core:charcoal_lump","mcl_trees:charcoal")
