local modpath = minetest.get_modpath(minetest.get_current_modname())

dofile(modpath.."/vlf_trees.lua")
dofile(modpath.."/vlf_doors.lua")
dofile(modpath.."/vlf_tools.lua")
dofile(modpath.."/vlf_dyes.lua")
dofile(modpath.."/vlf_copper.lua")
dofile(modpath.."/vlf_stairs.lua")
dofile(modpath.."/vlf_crimson.lua")
dofile(modpath.."/vlf_armor.lua")
dofile(modpath.."/vlf_panes.lua")
dofile(modpath.."/mesecons.lua")
dofile(modpath.."/vlfn_vlfo_aliases.lua")
