minetest.register_alias("3d_armor:helmet_leather", "vlf_armor:helmet_leather")
minetest.register_alias("3d_armor:helmet_iron", "vlf_armor:helmet_iron")
minetest.register_alias("3d_armor:helmet_chain", "vlf_armor:helmet_chain")
minetest.register_alias("3d_armor:helmet_gold", "vlf_armor:helmet_gold")
minetest.register_alias("3d_armor:helmet_diamond", "vlf_armor:helmet_diamond")

minetest.register_alias("3d_armor:chestplate_leather", "vlf_armor:chestplate_leather")
minetest.register_alias("3d_armor:chestplate_iron", "vlf_armor:chestplate_iron")
minetest.register_alias("3d_armor:chestplate_chain", "vlf_armor:chestplate_chain")
minetest.register_alias("3d_armor:chestplate_gold", "vlf_armor:chestplate_gold")
minetest.register_alias("3d_armor:chestplate_diamond", "vlf_armor:chestplate_diamond")

minetest.register_alias("3d_armor:leggings_leather", "vlf_armor:leggings_leather")
minetest.register_alias("3d_armor:leggings_iron", "vlf_armor:leggings_iron")
minetest.register_alias("3d_armor:leggings_chain", "vlf_armor:leggings_chain")
minetest.register_alias("3d_armor:leggings_gold", "vlf_armor:leggings_gold")
minetest.register_alias("3d_armor:leggings_diamond", "vlf_armor:leggings_diamond")

minetest.register_alias("3d_armor:boots_leather", "vlf_armor:boots_leather")
minetest.register_alias("3d_armor:boots_iron", "vlf_armor:boots_iron")
minetest.register_alias("3d_armor:boots_chain", "vlf_armor:boots_chain")
minetest.register_alias("3d_armor:boots_gold", "vlf_armor:boots_gold")
minetest.register_alias("3d_armor:boots_diamond", "vlf_armor:boots_diamond")
