local modname = minetest.get_current_modname()
local S = minetest.get_translator(modname)

return {
	{S("Creator of VoxelForge"), 0xFFD332, {
		"DragonWrangler1",
	}},
	{S("Creators of Mineclonia"), 0x0A9400, {
		"ryvnf",
		"cora",
	}},
	{S("Creator of MineClone 5"), 0xA6A6A6, {
		"kay27"
	}},
	{S("Creators of Voxelibre (Formerly Mineclone 2)"), 0x7C7A59, {
		"Wuzzy",
		"the-real-herowl",
		"ancientmarinerdev",
	}},
	{S("Creator of MineClone"), 0xFF51D5, {
		"davedevils",
	}},
	{S("Active Contributors"), 0xF84355, {
		"SamMatzko",
		"crispiebacon",
	}},
	{S("Previous Contributors"), 0x52FF00, {
		"Lizzy Fleckenstein",
		"NO11",
		"Brandon",
		"kay27",
		"marcin-serwin",
		"Michieal",
		"epCode",
		"PrairieWind",
		"chmodsayshello",
		"iliekprogrammar",
		"ancientmarinerdev",
		"TheOnlyJoeEnderman",
		"jordan4ibanez",
		"FossFanatic",
		"rubenwardy",
		"SumianVoice",
		"MysticTempest",
		"HimbeerserverDE",
		"MrRar",
		"kabou",
		"FaceDeer",
		"Nils Dagsson Moskopp",
		"ChrisPHP",
		"3raven",
	}},
	{S("Original Mod Authors"), 0xA60014, {
		"Wuzzy",
		"Fleckenstein",
		"BlockMen",
		"TenPlus1",
		"PilzAdam",
		"ryvnf",
		"stujones11",
		"Arcelmi",
		"celeron55",
		"maikerumine",
		"GunshipPenguin",
		"Qwertymine3",
		"Rochambeau",
		"rubenwardy",
		"stu",
		"4aiman",
		"Kahrl",
		"Krock",
		"UgnilJoZ",
		"lordfingle",
		"22i",
		"bzoss",
		"kilbith",
		"xeranas",
		"kddekadenz",
		"sofar",
		"4Evergreen4",
		"jordan4ibanez",
		"paramat",
		"cora",
		"DragonWrangler1",
	}},
	{S("3D Models"), 0x343434, {
		"22i",
		"tobyplowy",
		"epCode",
	}},
	{S("Textures and menu images"), 0x0019FF, {
		"XSSheep",
		"Wuzzy",
		"kingoscargames",
		"leorockway",
		"xMrVizzy",
		"yutyo",
		"NO11",
		"kay27",
		"MysticTempest",
		"RandomLegoBrick",
		"cora",
		"Michieal",
		"ryvnf",
		"SmokeyDope",
		"Aeonix_Aeon",
		"Nicu",
		"Exhale",
		"Aeonix_Aeon",
		"Wbjitscool",
		"SmokeyDope",
		"DragonWrangler1",
		"crispiebacon",
	}},
	{S("Translations"), 0xFF9705, {
		"Wuzzy",
		"Rocher Laurent",
		"wuniversales",
		"kay27",
		"pitchum",
		"todoporlalibertad",
		"Marcin Serwin",
		"Pepebotella",
		"Emojigit",
		"snowyu",
		"3raven",
		"Riu Sakura",
	}},
	{S("Special thanks"), 0x00FF60, {
		"celeron55 for creating Minetest",
		"Sn0wShepherd for making the very nice MineCraft themed music from the Sn0wSong resource pack",
		"The workaholics who spent way too much time writing for the Minecraft Wiki.",
		"Notch and Jeb for being the major forces behind Minecraft",
	}},
}
