unused_args = false
allow_defined_top = true
max_line_length = false
redefined = false
ignore = {
	--this is used intentionally in the codebase sometimes
	"512", -- Loop can be executed at most once.
}
globals = {
	"minetest", "core",
	"doc",
	"tt",
	"mesecon",
	"vlf_lightning",
	"controls",
	"flowlib",
	"awards",
	"mobs_mc",
	"screwdriver",
	"playerphysics",
	"vlf_panes",
	"tnt",
	"hb",
	"tsm_railcorridors",
	"tga_encoder",
	"hb",
	"walkover",
	"vlf_achievements",
	"vlf_amethyst",
	"vlf_anvils",
	"vlf_armor",
	"vlf_armor_stand",
	"vlf_attached",
	"_vlf_autogroup",
	"vlf_autogroup",
	"vlf_bamboo",
	"vlf_banners",
	"vlf_barrels",
	"vlf_base_textures",
	"vlf_beacons",
	"vlf_beds",
	"vlf_beehives",
	"vlf_bells",
	"vlf_biomes",
	"vlf_blackstone",
	"vlf_blast_furnace",
	"vlf_boats",
	"vlf_bone_meal",
	"vlf_books",
	"vlf_bossbars",
	"vlf_bows",
	"vlf_brewing",
	"vlf_buckets",
	"vlf_burning",
	"vlf_cake",
	"vlf_campfires",
	"vlf_cartography_table",
	"vlf_cauldrons",
	"vlf_cherry_blossom",
	"vlf_chests",
	"vlf_clock",
	"vlf_cocoas",
	"vlf_colorblocks",
	"vlf_colors",
	"vlf_commands",
	"vlf_comparators",
	"vlf_compass",
	"vlf_composters",
	"vlf_copper",
	"vlf_core",
	"vlf_craftguide",
	"vlf_crafting_table",
	"vlf_credits",
	"vlf_crimson",
	"vlf_criticals",
	"vlf_curry",
	"vlf_damage",
	"vlf_death_drop",
	"vlf_death_messages",
	"vlf_deepslate",
	"vlf_dispensers",
	"vlf_doc",
	"vlf_doc_basics",
	"vlf_doors",
	"vlf_dripping",
	"vlf_droppers",
	"vlf_dungeons",
	"vlf_dyes",
	"vlf_enchanting",
	"vlf_end",
	"vlf_end_island",
	"vlf_entity_invs",
	"vlf_events",
	"vlf_experience",
	"vlf_explosions",
	"vlf_falling_nodes",
	"vlf_farming",
	"vlf_fences",
	"vlf_fire",
	"vlf_fireworks",
	"vlf_fishing",
	"vlf_fletching_table",
	"vlf_flowerpots",
	"vlf_flowers",
	"vlf_formspec",
	"vlf_formspec_prepend",
	"vlf_furnaces",
	"vlf_gamemode",
	"vlf_grindstone",
	"vlf_hbarmor",
	"vlf_heads",
	"vlf_honey",
	"vlf_hoppers",
	"vlf_hunger",
	"vlf_info",
	"vlf_init",
	"vlf_inventory",
	"vlf_item_entity",
	"vlf_itemframes",
	"vlf_item_id",
	"vlf_jukebox",
	"vlf_lanterns",
	"vlf_lectern",
	"vlf_lightning_rods",
	"vlf_loom",
	"vlf_loot",
	"vlf_mangrove",
	"vlf_mapgen_core",
	"vlf_maps",
	"vlf_meshhand",
	"vlf_minecarts",
	"vlf_mobitems",
	"vlf_mobs",
	"vlf_mobspawners",
	"vlf_monster_eggs",
	"vlf_moon",
	"vlf_mud",
	"vlf_mushrooms",
	"vlf_nether",
	"vlf_nether_fortresses",
	"vlf_observers",
	"vlf_ocean",
	"vlf_offhand",
	"vlf_paintings",
	"vlf_particles",
	"vlf_player",
	"vlf_playerinfo",
	"vlf_player_init",
	"vlf_playerplus",
	"vlf_portals",
	"vlf_potions",
	"vlf_pottery_sherds",
	"vlf_privs",
	"vlf_raids",
	"vlf_raw_ores",
	"vlf_sculk",
	"vlf_shields",
	"vlf_signs",
	"vlf_skins",
	"vlf_smithing_table",
	"vlf_smoker",
	"vlf_sounds",
	"vlf_spawn",
	"vlf_sponges",
	"vlf_sprint",
	"vlf_spyglass",
	"vlf_stairs",
	"vlf_stonecutter",
	"vlf_strongholds",
	"vlf_structures",
	"vlf_sus_stew",
	"vlf_target",
	"vlf_temp_helper_recipes",
	"vlf_terrain_features",
	"vlf_throwing",
	"vlf_title",
	"vlf_tnt",
	"vlf_tools",
	"vlf_torches",
	"vlf_totems",
	"vlf_trees",
	"vlf_tt",
	"vlf_util",
	"vlf_villages",
	"vlf_void_damage",
	"vlf_walls",
	"vlf_weather",
	"vlf_wieldview",
	"vlf_wip",
	"vlf_wither_spawning",
	"vlf_wool",
	"vlf_worlds",
	"vlf_zombie_sieges",
	"vlf_lush_caves",
	"vlf_armor_trims",
	"vlf_villages",
	"vlf_trials",
	"vlf_textures",
	"vlf_json",
	"vlf_tridents",
	"vlf_bundles",
	"AreaStore",
}

exclude_files = {
	"mods/PLAYER/vlf_music/init.lua",
	"mods/ITEMS/vlf_bubble_column/init.lua",
	"mods/ITEMS/vlf_sculk/init.lua",
	"pattern/*"
}

read_globals = {
	"DIR_DELIM",
	"dump", "dump2",
	"vector",
	"VoxelManip", "VoxelArea",
	"PseudoRandom", "PcgRandom", "PerlinNoise", "PerlinNoiseMap",
	"ItemStack",
	"Settings",
	"unpack",

	table = {
		fields = {
			update = { read_only = false },
			update_nil = { read_only = false },
			merge = { read_only = false },
			"copy",
			"indexof",
			"insert_all",
			"key_value_swap",
			"shuffle",
			reverse = { read_only = false },
			count = { read_only = false },
			random_element = { read_only = false },
		}
	},

	string = {
		fields = {
			"split",
			"trim",
		}
	},

	math = {
		fields = {
			"hypot",
			"sign",
			"factorial",
			"round",
		}
	},
	------
	--MODS
	------

	--CORE
	"vlf_vars",

	--GENERAL
	"default",


	--ENTITIES
	"cmi",

	--HUD

	"cmsg",

	"sfinv", "sfinv_buttons", "unified_inventory", "cmsg", "inventory_plus",
}
