minetest.register_alias("mcl_trees:bark_bamboo", "mcl_trees:tree_bamboo")
minetest.register_alias("mcl_trees:bark_stripped_bamboo", "mcl_trees:stripped_bamboo")
minetest.register_alias("mcl_stairs:slab_bamboo_bark", "mcl_stairs:slab_bamboo")
minetest.register_alias("mcl_stairs:slab_bamboo_bark_double", "mcl_stairs:slab_bamboo_double")
minetest.register_alias("mcl_stairs:slab_bamboo_bark_top", "mcl_stairs:slab_bamboo_top")
minetest.register_alias("mcl_stairs:stair_bamboo_bark", "mcl_stairs:stair_bamboo")
minetest.register_alias("mcl_stairs:stair_bamboo_bark_inner", "mcl_stairs:stair_bamboo_inner")
minetest.register_alias("mcl_stairs:stair_bamboo_bark_outer", "mcl_stairs:stair_bamboo_outer")
