local modname = minetest.get_current_modname()
local S = minetest.get_translator(modname)

return {
    {S("Creator of VoxelForge"), 0xFFD332, {
		"DragonWrangler1",
	}},
	{S("Creators of Mineclonia"), 0x0A9400, {
		"ryvnf",
		"cora",
	}},
	{S("Creator of MineClone 2"), 0xFFFFFF, {
		"Wuzzy",
	}},
	{S("Creator of MineClone"), 0xFF51D5, {
		"davedevils",
	}},
	{S("Active Contributors"), 0xF84355, {
		"codiac",
		"JoseDouglas26",
		"Brama Udi",
		"ellesheepy",
		"Jürgen Rühle",
		"kno10",
		"Po Lu",
		"goblin_mode",
		"Lars Müller",
		"the-real-herowl",
		"nooneatall",
	}},
	{S("Previous Contributors"), 0x52FF00, {
		"Lizzy Fleckenstein",
		"AFCMS",
		"NO11",
		"Brandon",
		"kay27",
		"marcin-serwin",
		"Michieal",
		"epCode",
		"PrairieWind",
		"chmodsayshello",
		"iliekprogrammar",
		"ancientmarinerdev",
		"TheOnlyJoeEnderman",
		"jordan4ibanez",
		"FossFanatic",
		"rubenwardy",
		"SumianVoice",
		"MysticTempest",
		"HimbeerserverDE",
		"MrRar",
		"kabou",
		"FaceDeer",
		"Nils Dagsson Moskopp",
		"ChrisPHP",
		"3raven",
		"ShadowRoi",
		"crispiebacon",
		"amino",
		"teknomunk",
		"nixnoxus",
		"laireia",
		"Eliy21",
		"ROllerozxa",
	}},
	{S("Original Mod Authors"), 0xA60014, {
		"Wuzzy",
		"Fleckenstein",
		"BlockMen",
		"TenPlus1",
		"PilzAdam",
		"ryvnf",
		"stujones11",
		"Arcelmi",
		"celeron55",
		"maikerumine",
		"GunshipPenguin",
		"Qwertymine3",
		"Rochambeau",
		"rubenwardy",
		"stu",
		"4aiman",
		"Kahrl",
		"Krock",
		"UgnilJoZ",
		"lordfingle",
		"22i",
		"bzoss",
		"kilbith",
		"xeranas",
		"kddekadenz",
		"sofar",
		"4Evergreen4",
		"jordan4ibanez",
		"paramat",
		"cora",
        "DragonWrangler1",
	}},
	{S("3D Models"), 0x343434, {
		"22i",
		"tobyplowy",
		"epCode",
		"pixelzone",
        "DragonWrangler1",
        "crispiebacon",
	}},
	{S("Textures and menu images"), 0x0019FF, {
		"XSSheep",
		"Wuzzy",
		"kingoscargames",
		"leorockway",
		"xMrVizzy",
		"yutyo",
		"NO11",
		"kay27",
		"MysticTempest",
		"RandomLegoBrick",
		"cora",
		"Michieal",
		"ryvnf",
		"SmokeyDope",
		"Aeonix_Aeon",
		"Nicu",
		"Exhale",
		"Aeonix_Aeon",
		"Wbjitscool",
		"SmokeyDope",
		"pixelzone",
        "crispiebacon",
        "DragonWrangler1"
	}},
	{S("Translations"), 0xFF9705, {
		"Wuzzy",
		"Rocher Laurent",
		"wuniversales",
		"kay27",
		"pitchum",
		"todoporlalibertad",
		"Marcin Serwin",
		"Pepebotella",
		"Emojigit",
		"snowyu",
		"3raven",
		"Riu Sakura",
		"3raven",
		"Ame-chan-angel",
		"Application-Maker",
		"Benny",
		"collectanos",
		"Cwpute",
		"Dirk",
		"Enlive",
		"fnetX",
		"Gaemy",
		"hugoalh",
		"j-r",
		"Kyoushi",
		"liulitchi",
		"mugcake",
		"phileas",
		"Pietro Cappuccino",
		"RadonPrunus",
		"Sencyy",
		"Sotis",
		"Zozosticot",
		"ellesheepy",
		"bright",
		"Miguel P.L",
		"Just Playing",
		"JoseDouglas26",
		"bramaudi",
		"balazsszalab",
		"milklikecomputer",
		"CodePoet2005",
		"real_mineplayer",
	}},
	{S("Special thanks"), 0x00FF60, {
		"celeron55 for creating Luanti (Minetest)",
		"Jordach for the jukebox music compilation from Big Freaking Dig",
		"The workaholics who spent way too much time writing for the Minecraft Wiki.",
		"Notch and Jeb for being the major forces behind Minecraft",
	}},
}
