---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by michieal.
--- DateTime: 12/29/22 12:46 PM -- Restructure Date
--- These are all of the fuel recipes and all of the crafting recipes, consolidated into one place.
--- Copyright (C) 2022 - 2023, Michieal. See License.txt

minetest.register_craft({
	output = "mcl_core:stick",
	recipe = {
		{"mcl_bamboo:bamboo"},
		{"mcl_bamboo:bamboo"},
	}
})

minetest.register_craft({
	output = "mcl_bamboo:bamboo_block",
	recipe = {
		{"mcl_bamboo:bamboo", "mcl_bamboo:bamboo", "mcl_bamboo:bamboo"},
		{"mcl_bamboo:bamboo", "mcl_bamboo:bamboo", "mcl_bamboo:bamboo"},
		{"mcl_bamboo:bamboo", "mcl_bamboo:bamboo", "mcl_bamboo:bamboo"},
	}
})

minetest.register_craft({
	output = "mcl_bamboo:bamboo_plank 2",
	recipe = {
		{"mcl_bamboo:bamboo_block"},
	}
})

minetest.register_craft({
	output = "mcl_bamboo:bamboo_plank 2",
	recipe = {
		{"mcl_bamboo:bamboo_block_stripped"},
	}
})

minetest.register_craft({
	output = "mcl_bamboo:bamboo_mosaic",
	recipe = {
		{"mcl_stairs:slab_bamboo_plank"},
		{"mcl_stairs:slab_bamboo_plank"},
	}
})

minetest.register_craft({
	output = "mcl_bamboo:bamboo_door 3",
	recipe = {
		{"mcl_bamboo:bamboo_plank", "mcl_bamboo:bamboo_plank"},
		{"mcl_bamboo:bamboo_plank", "mcl_bamboo:bamboo_plank"},
		{"mcl_bamboo:bamboo_plank", "mcl_bamboo:bamboo_plank"}
	}
})
minetest.register_craft({
	output = "mcl_bamboo:bamboo_trapdoor 2",
	recipe = {
		{"mcl_bamboo:bamboo_plank", "mcl_bamboo:bamboo_plank", "mcl_bamboo:bamboo_plank"},
		{"mcl_bamboo:bamboo_plank", "mcl_bamboo:bamboo_plank", "mcl_bamboo:bamboo_plank"},
	}
})


minetest.register_craft({
	output = "mcl_bamboo:bamboo_fence 3",
	recipe = {
		{"mcl_bamboo:bamboo_plank", "mcl_core:stick", "mcl_bamboo:bamboo_plank"},
		{"mcl_bamboo:bamboo_plank", "mcl_core:stick", "mcl_bamboo:bamboo_plank"},
	}
})
minetest.register_craft({
	output = "mcl_bamboo:bamboo_fence_gate",
	recipe = {
		{"mcl_core:stick", "mcl_bamboo:bamboo_plank", "mcl_core:stick"},
		{"mcl_core:stick", "mcl_bamboo:bamboo_plank", "mcl_core:stick"},
	}
})

minetest.register_craft({
	output = "mcl_bamboo:scaffolding 6",
	recipe = {{"mcl_bamboo:bamboo", "mcl_mobitems:string", "mcl_bamboo:bamboo"},
			  {"mcl_bamboo:bamboo", "", "mcl_bamboo:bamboo"},
			  {"mcl_bamboo:bamboo", "", "mcl_bamboo:bamboo"}}
})

minetest.register_craft({
	type = "fuel",
	recipe = "mcl_bamboo:bamboo",
	burntime = 2.5,
})

minetest.register_craft({
	type = "fuel",
	recipe = "mcl_bamboo:bamboo_block",
	burntime = 15,
})

minetest.register_craft({
	type = "fuel",
	recipe = "mcl_bamboo:bamboo_block_stripped",
	burntime = 15,
})

minetest.register_craft({
	type = "fuel",
	recipe = "mcl_bamboo:bamboo_plank",
	burntime = 7.5,
})

minetest.register_craft({
	type = "fuel",
	recipe = "mcl_bamboo:bamboo_mosaic",
	burntime = 7.5,
})

-- Bamboo Items
if minetest.get_modpath("mcl_doors") then
	if mcl_doors then
		minetest.register_craft({
			type = "fuel",
			recipe = "mcl_bamboo:bamboo_door",
			burntime = 10,
		})

		minetest.register_craft({
			type = "fuel",
			recipe = "mcl_bamboo:bamboo_trapdoor",
			burntime = 15,
		})
	end
end

minetest.register_craft({
	type = "fuel",
	recipe = "mcl_stairs:slab_bamboo_plank",
	burntime = 7.5,
})
minetest.register_craft({
	type = "fuel",
	recipe = "mcl_stairs:slab_bamboo_block",
	burntime = 7.5,
})
minetest.register_craft({
	type = "fuel",
	recipe = "mcl_stairs:slab_bamboo_stripped",
	burntime = 7.5,
})
minetest.register_craft({
	type = "fuel",
	recipe = "mcl_stairs:stair_bamboo_plank",
	burntime = 15,
})
minetest.register_craft({
	type = "fuel",
	recipe = "mcl_stairs:stair_bamboo_block",
	burntime = 15,
})
minetest.register_craft({
	type = "fuel",
	recipe = "mcl_stairs:stair_bamboo_stripped",
	burntime = 15,
})
minetest.register_craft({
	type = "fuel",
	recipe = "mcl_stairs:slab_bamboo_mosaic",
	burntime = 7.5,
})
minetest.register_craft({
	type = "fuel",
	recipe = "mcl_stairs:stair_bamboo_mosaic",
	burntime = 15,
})

minetest.register_craft({
	type = "fuel",
	recipe = "mesecons_button:button_bamboo_off",
	burntime = 5,
})

minetest.register_craft({
	type = "fuel",
	recipe = "mcl_bamboo:scaffolding",
	burntime = 20
})
