local modname = minetest.get_current_modname()
local S = minetest.get_translator(modname)

return {
	{S("Creators of Mineclonia"), 0x0A9400, {
		"ryvnf",
		"cora",
	}},
	{S("Creator of MineClone2"), 0xFBF837, {
		"Wuzzy",
	}},
	{S("Creator of MineClone"), 0xFF51D5, {
		"davedevils",
	}},
	{S("Active Contributors"), 0xF84355, {
		"Michieal",
		"TheOnlyJoeEnderman",
		"ancientmarinerdev",
		"FossFanatic",
		"Michieal",
		"PrairieWind",
		"epCode",
		"anarquimico",
		"AFCMS",
		"Johannes Fritz",
	}},
	{S("Previous Contributors"), 0x52FF00, {
		"Elias Fleckenstein",
		"NO11",
		"davedevils",
		"kay27",
		"Brandon",
		"marcin-serwin",
		"chmodsayshello",
		"iliekprogrammar",
		"bzoss",
		"jordan4ibanez",
		"epCode",
		"SumianVoice",
		"MysticTempest",
		"HimbeerserverDE",
		"kay27",
		"FaceDeer",
		"kabou",
		"3raven",
	}},
	{S("Original Mod Authors"), 0xA60014, {
		"Wuzzy",
		"Fleckenstein",
		"BlockMen",
		"TenPlus1",
		"PilzAdam",
		"ryvnf",
		"stujones11",
		"Arcelmi",
		"celeron55",
		"maikerumine",
		"GunshipPenguin",
		"Qwertymine3",
		"Rochambeau",
		"rubenwardy",
		"stu",
		"4aiman",
		"Kahrl",
		"Krock",
		"UgnilJoZ",
		"lordfingle",
		"22i",
		"bzoss",
		"kilbith",
		"xeranas",
		"kddekadenz",
		"sofar",
		"4Evergreen4",
		"jordan4ibanez",
		"paramat",
		"cora",
	}},
	{S("3D Models"), 0x343434, {
		"22i",
		"tobyplowy",
		"epCode",
	}},
	{S("Textures and menu images"), 0x0019FF, {
		"XSSheep",
		"Wuzzy",
		"kingoscargames",
		"leorockway",
		"xMrVizzy",
		"yutyo",
		"NO11",
		"kay27",
		"MysticTempest",
		"RandomLegoBrick",
		"cora",
		"Faerraven / Michieal",
		"Nicu",
		"ryvnf",
	}},
	{S("Translations"), 0xFF9705, {
		"Wuzzy",
		"Rocher Laurent",
		"wuniversales",
		"kay27",
		"pitchum",
		"todoporlalibertad",
		"Marcin Serwin",
		"Pepebotella",
		"Emojigit",
		"snowyu",
		"3raven",
		"SakuraRiu",
		"anarquimico",
		"syl",
	}},
	{S("Special thanks"), 0x00FF60, {
		"celeron55 for creating Minetest",
		"Jordach for the jukebox music compilation from Big Freaking Dig",
		"The workaholics who spent way too much time writing for the Minecraft Wiki.",
		"Notch and Jeb for being the major forces behind Minecraft",
	}},
}
