local modpath = minetest.get_modpath(minetest.get_current_modname())

dofile(modpath.."/vlc_trees.lua")
dofile(modpath.."/vlc_doors.lua")
dofile(modpath.."/vlc_tools.lua")
dofile(modpath.."/vlc_dyes.lua")
dofile(modpath.."/vlc_copper.lua")
dofile(modpath.."/vlc_stairs.lua")
dofile(modpath.."/vlc_crimson.lua")
dofile(modpath.."/vlc_armor.lua")
dofile(modpath.."/vlc_panes.lua")
dofile(modpath.."/mesecons.lua")
