local modpath = minetest.get_modpath(minetest.get_current_modname())

minetest.register_alias("mc2mt:tuff_bricks","vlf_deepslate:tuff_bricks")
minetest.register_alias("mc2mt:chiseled_tuff_bricks", "vlf_deepslate:chiseled_tuff_bricks")
minetest.register_alias("mc2mt:waxed_copper_grate", "vlf_copper:waxed_copper_grate")
minetest.register_alias("mc2mt:polished_tuff", "vlf_deepslate:polished_tuff")
minetest.register_alias("vlf_core:dirt_with_grass","vlf_core:dirt_with_grass")
minetest.register_alias("mc2mt:waxed_oxidized_copper","vlf_copper:waxed_oxidized_copper")
minetest.register_alias("vlf_signs:standing_sign_oak", "vlf_signs:standing_sign_oak")
minetest.register_alias("vlf_core:ladder", "vlf_core:ladder")
minetest.register_alias("mc2mt:waxed_oxidized_cut_copper", "vlf_copper:waxed_oxidized_cut_copper")
minetest.register_alias("mc2mt:chiseled_tuff", "vlf_deepslate:chiseled_tuff")
minetest.register_alias("mc2mt:waxed_copper_bulb", "vlf_copper:waxed_copper_bulb_lit")
minetest.register_alias("mc2mt:waxed_exposed_copper_bulb", "vlf_copper:waxed_exposed_copper_bulb_lit")
minetest.register_alias("mc2mt:waxed_chiseled_copper", "vlf_copper:waxed_chiseled_copper")
minetest.register_alias("wood", "vlf_copper:waxed_copper")

minetest.register_alias("vlf_deepslate:deepslate_with_coal", "vlf_deepslate:deepslate_coal_ore")
minetest.register_alias("vlf_deepslate:deepslate_with_copper", "vlf_deepslate:deepslate_copper_ore")
minetest.register_alias("vlf_deepslate:deepslate_with_diamond", "vlf_deepslate:deepslate_diamond_ore")
minetest.register_alias("vlf_deepslate:deepslate_with_gold", "vlf_deepslate:deepslate_gold_ore")
minetest.register_alias("vlf_deepslate:deepslate_with_iron", "vlf_deepslate:deepslate_iron_ore")
minetest.register_alias("vlf_deepslate:deepslate_with_redstone", "vlf_deepslate:deepslate_redstone_ore")
