minetest.register_alias("mc2mt:waxed_copper_grate", "vlf_copper:waxed_copper_grate")
minetest.register_alias("mc2mt:polished_tuff", "vlf_deepslate:polished_tuff")
minetest.register_alias("mcl_core:dirt_with_grass","vlf_core:dirt_with_grass")
minetest.register_alias("mc2mt:waxed_oxidized_copper","vlf_copper:waxed_oxidized_copper")
minetest.register_alias("mcl_signs:standing_sign_oak", "vlf_signs:standing_sign_oak")
minetest.register_alias("mcl_core:ladder", "vlf_core:ladder")
minetest.register_alias("mc2mt:waxed_oxidized_cut_copper", "vlf_copper:waxed_oxidized_cut_copper")
minetest.register_alias("mc2mt:chiseled_tuff", "vlf_deepslate:chiseled_tuff")
minetest.register_alias("mc2mt:waxed_copper_bulb", "vlf_copper:waxed_copper_bulb_lit")
minetest.register_alias("mc2mt:waxed_exposed_copper_bulb", "vlf_copper:waxed_exposed_copper_bulb_lit")
minetest.register_alias("mc2mt:waxed_chiseled_copper", "vlf_copper:waxed_chiseled_copper")
minetest.register_alias("mc2mt:chiseled_tuff_bricks", "vlf_deepslate:tuff_chiseled_bricks")
minetest.register_alias("mc2mt:chiseled_tuff", "vlf_deepslate:tuff_chiseled")
minetest.register_alias("mc2mt:polished_tuff", "vlf_deepslate:tuff_polished")
minetest.register_alias("mc2mt:tripwire", "vlf_tripwire:tripwire")
minetest.register_alias("mc2mt:tripwire_hook", "vlf_tripwire:tripwire_hook")
minetest.register_alias("wood", "vlf_copper:waxed_copper")
minetest.register_alias("mcl_core:leaves", "vlf_trees:leaves_oak")
minetest.register_alias("mcl_core:tree", "vlf_trees:tree_oak")
minetest.register_alias("mcl_core:water_source", "vlf_core:water_source")
minetest.register_alias("stairs:stair_wood", "vlf_stairs:stair_waxed_copper_oxidized_cut")
minetest.register_alias("mc2mt:tuff_bricks", "vlf_deepslate:tuff_bricks")
minetest.register_alias("mcl_core:mossycobble", "vlf_core:mossycobble")
minetest.register_alias("mcl_core:glass_silver", "vlf_core:glass_silver")
minetest.register_alias("mcl_dispensers:dispenser", "vlf_dispensers:dispenser")

minetest.register_alias("vlf_deepslate:deepslate_with_coal", "vlf_deepslate:deepslate_coal_ore")
minetest.register_alias("vlf_deepslate:deepslate_with_copper", "vlf_deepslate:deepslate_copper_ore")
minetest.register_alias("vlf_deepslate:deepslate_with_diamond", "vlf_deepslate:deepslate_diamond_ore")
minetest.register_alias("vlf_deepslate:deepslate_with_gold", "vlf_deepslate:deepslate_gold_ore")
minetest.register_alias("vlf_deepslate:deepslate_with_iron", "vlf_deepslate:deepslate_iron_ore")
minetest.register_alias("vlf_deepslate:deepslate_with_redstone", "vlf_deepslate:deepslate_redstone_ore")
