local modpath = minetest.get_modpath(minetest.get_current_modname())

minetest.register_alias("mc2mt:tuff_bricks","vlc_deepslate:tuff_bricks")
minetest.register_alias("mc2mt:chiseled_tuff_bricks", "vlc_deepslate:chiseled_tuff_bricks")
minetest.register_alias("mc2mt:waxed_copper_grate", "vlc_copper:waxed_copper_grate")
minetest.register_alias("mc2mt:polished_tuff", "vlc_deepslate:polished_tuff")
minetest.register_alias("mcl_core:dirt_with_grass","vlc_core:dirt_with_grass")
minetest.register_alias("mc2mt:waxed_oxidized_copper","vlc_copper:waxed_oxidized_copper")
minetest.register_alias("mcl_signs:standing_sign_oak", "vlc_signs:standing_sign_oak")
minetest.register_alias("mcl_core:ladder", "vlc_core:ladder")
minetest.register_alias("mc2mt:waxed_oxidized_cut_copper", "vlc_copper:waxed_oxidized_cut_copper")
minetest.register_alias("mc2mt:chiseled_tuff", "vlc_deepslate:chiseled_tuff")
minetest.register_alias("mc2mt:waxed_copper_bulb", "vlc_copper:waxed_copper_bulb_lit")
minetest.register_alias("mc2mt:waxed_exposed_copper_bulb", "vlc_copper:waxed_exposed_copper_bulb_lit")
minetest.register_alias("mc2mt:waxed_chiseled_copper", "vlc_copper:waxed_chiseled_copper")
minetest.register_alias("wood", "vlc_copper:waxed_copper")
